### ISSUE TITLE
Plugin don't show up in WP

### ISSUE THREAD

**Issue by craftercis** [kucrut/vite-for-wp#18]
Hey.

I can't see my plugin in the list of plugins in Wordpress. Is it possible that you can put a test plugin on your GitHub so I can download it and see what I'm doing wrong.

I'm trying to make a plugin that uses vite react and load it in wordpress. But I do something wrong here :)

EDIT:
I see you made Catatan. But if you have time, can you make a basic vite-react plugin with this method that loads the react app in a footer?

**Comment by kucrut** [comment]
Hey @craftercis!

I've created an example plugin here https://github.com/kucrut/vite-for-wp-example-react

Thanks to your request, I found a bug and issued a fix :tada:
