### ISSUE TITLE
Vite server not stopping after a Ctrl+c

### ISSUE THREAD

**Issue by mickaelchanrion** [kucrut/vite-for-wp#22]
Hi there!

Thanks a lot for this nice module. Very helpful!

I noticed that the vite server doesn't seem to be killed once the process is exited (Ctrl+C).
Because if I start vite again, the port will increment.

e.g.:
```sh
$ yarn dev # Local: http://127.0.0.1:5173/
# ˆC
$ yarn dev # Local: http://127.0.0.1:5174/
# ˆC
```

**Comment by kucrut** [comment]
Hi @mickaelchanrion,

Can you update to the latest version (including the dependencies) and test it again?  I'm not experiencing this issue.

**Comment by kucrut** [comment]
OH: I can now reproduce it with `yarn`. Running it with `pnpm` works just fine. I'll have a look.
