### ISSUE TITLE
Implement in plugin Admin

### ISSUE THREAD

**Issue by jremen** [kucrut/vite-for-wp#34]
Hi,
how can I implement this in the wordpress admin part for a plugin?
I'm developing plugin solely with React for it's administration and settings.
When I enqueue script (generated to some .js) it works just fine, but my dynamic imports from JSX cease to work properly even if generated .js file has correct reference to them

**Comment by kucrut** [comment]
Hi @jremen,

Is it possible for you to provide a minimal reproducible plugin so I can debug it?

**Comment by kucrut** [comment]
Closing this issue for the lack of example/reproduction steps. Please feel free to reopen with an example plugin to reproduce the issue.
