### ISSUE TITLE
How to load dotevn variables?

### ISSUE THREAD

**Issue by asolopovas** [kucrut/vite-for-wp#40]
Does your plugin has ability to load dotenv variables from .env file?

**Comment by multiplehats** [comment]
I don't think it has anything to do with this package.

It's really easy to import env variables in Vite: https://vitejs.dev/guide/env-and-mode.html

**Comment by kucrut** [comment]
Yep, like @multiplehats said, you can follow Vite's official guide on how to load env variables.
