### ISSUE TITLE
Release 0.8

### ISSUE THREAD

**Issue by johnbillion** [kucrut/vite-for-wp#72]
Hey Dzikri! Hope you're well.

I see version 0.8 is not yet released. The `main` branch contains some fixes for bugs that I've experienced, primarily the duplication of the React preamble script when more than one asset is enqueued on the page.

Is there a plan to release version 0.8?

**Comment by kucrut** [comment]
Hey John! I'm doing well, thanks.

0.8.0 is out. Enjoy! :tada:
