### ISSUE TITLE
Option not to delete manifest.json.

### ISSUE THREAD

**Issue by asolopovas** [kucrut/vite-for-wp#75]
Hi,

I was wondering if you would consider adding an option to avoid executing the following:

```javascript
buildEnd() {
    rmSync(manifest_file, { force: true });
}
```

The issue arises when built files are committed to source control and manifest.json is used to load assets in WordPress. If the development server is run with the intention of making modifications, which might not be committed to production, it results in the removal of manifest.json. This disrupts the existing asset loading. Consequently, I have to either run the production script to restore it or use Git to recover the file after running the development script. It would be more convenient to leave the repository unchanged after running development, simply to avoid unnecessary actions.

**Comment by kucrut** [comment]
@asolopovas The code block you quoted is to remove the manifest file generated by the dev server, not the build command. Your build directory and its manifest file shouldn't be removed by running dev server.

**Comment by asolopovas** [comment]
I have migrated to roots bud.js they use webpack but hmr works and it seems to be really fast and works out of the box, so I given up on trying to make it work with vite, literally no time so don't care about the issue. Maybe I was stupid and done something I did not know.
