### ISSUE TITLE
[BUG] Manifest is created in wrong directory after build

### ISSUE THREAD

**Issue by j7-dev** [kucrut/vite-for-wp#80]
Hello, 

I am grateful for your contributions. 🙏

I found a bug after I run `yarn build‵

#### Problem in `"kucrut/vite-for-wp": "^0.8.0"`

`manifest.json` will be created in `dist/.vite` directory which is WRONG

![image](https://github.com/kucrut/vite-for-wp/assets/9213776/ec914a0c-7bde-4734-9a4d-d11803550019)

[function get_manifest](https://github.com/kucrut/vite-for-wp/blob/bce4607bb57f4892da93492908caeb75ce2782a2/vite-for-wp.php#L29C10-L29C22) will try to find the manifest file in `__DIR__ . '/js/dist'`, NOT in `__DIR__ . '/js/dist/.vite'`

That will cause an error, lead to empty assets, so the built js won't be enqueue.

#### No problem in `"kucrut/vite-for-wp": "^0.5.2"`

![image](https://github.com/kucrut/vite-for-wp/assets/9213776/673ee63d-06d3-4b2a-89ee-173f286b991c)

---

### Update

It seems the `manifest.json` will be created in `dist/.vite` in vite 5

reference
https://github.com/nystudio107/craft-vite/issues/77
https://www.drupal.org/project/vite/issues/3401054

**Comment by j7-dev** [comment]
I resolve this with this commonJS temporary.

move `dist/.vite/manifest.json` to `dist/manifest.json`

https://github.com/j7-dev/wp-react-plugin/blob/master/release/mv-manifest.cjs

**Comment by kucrut** [comment]
This is fixed in #92.
